const VN_MATH_CURRICULUM = {
  6: {
    'Chương 1. Số tự nhiên': ['Tập hợp', 'Số tự nhiên', 'Phép tính', 'Lũy thừa', 'Thứ tự thực hiện phép tính'],
    'Chương 2. Tính chia hết': ['Quan hệ chia hết', 'Ước và bội', 'Số nguyên tố', 'Phân tích số', 'ƯCLN', 'BCNN'],
    'Chương 3. Số nguyên': ['Số nguyên', 'Trục số', 'Giá trị tuyệt đối', 'Phép cộng', 'Phép trừ', 'Phép nhân', 'Phép chia'],
    'Chương 4. Hình học trực quan': ['Điểm', 'Đường thẳng', 'Đoạn thẳng', 'Góc', 'Tam giác', 'Hình vuông', 'Hình chữ nhật'],
    'Chương 5. Đối xứng': ['Đối xứng trục', 'Đối xứng tâm'],
    'Chương 6. Phân số': ['Phân số', 'So sánh', 'Quy đồng', 'Các phép tính'],
    'Chương 7. Số thập phân': ['Số thập phân', 'Phép tính', 'Tỉ số', 'Phần trăm'],
    'Chương 8. Dữ liệu và xác suất': ['Thu thập dữ liệu', 'Bảng thống kê', 'Biểu đồ', 'Xác suất thực nghiệm'],
  },
  7: {
    'Chương 1. Số hữu tỉ': ['Tập hợp số hữu tỉ', 'Biểu diễn số hữu tỉ trên trục số', 'So sánh số hữu tỉ', 'Cộng số hữu tỉ', 'Trừ số hữu tỉ', 'Nhân số hữu tỉ', 'Chia số hữu tỉ', 'Lũy thừa của số hữu tỉ'],
    'Chương 2. Số thực': ['Số vô tỉ', 'Căn bậc hai số học', 'Số thực', 'Giá trị tuyệt đối', 'Làm tròn số', 'Ước lượng'],
    'Chương 3. Góc và đường thẳng': ['Góc', 'Góc kề, góc đối đỉnh', 'Hai đường thẳng song song', 'Dấu hiệu nhận biết hai đường thẳng song song', 'Tiên đề Euclid'],
    'Chương 4. Tam giác': ['Tổng ba góc của tam giác', 'Các trường hợp bằng nhau của tam giác', 'Tam giác cân', 'Tam giác đều', 'Tam giác vuông'],
    'Chương 5. Quan hệ trong tam giác': ['Quan hệ giữa cạnh và góc', 'Đường vuông góc', 'Đường trung trực', 'Đường trung tuyến', 'Đường phân giác', 'Đường cao'],
    'Chương 6. Đại lượng tỉ lệ': ['Đại lượng tỉ lệ thuận', 'Đại lượng tỉ lệ nghịch', 'Hàm số', 'Đồ thị'],
    'Chương 7. Biểu thức đại số': ['Biểu thức đại số', 'Đơn thức', 'Đa thức', 'Cộng trừ đa thức', 'Nghiệm của đa thức'],
    'Chương 8. Thống kê và xác suất': ['Thu thập dữ liệu', 'Bảng số liệu', 'Biểu đồ', 'Biến cố', 'Xác suất thực nghiệm'],
  },
  8: {
    'Chương 1. Biểu thức đại số': ['Đơn thức', 'Đa thức nhiều biến', 'Phép cộng', 'Phép trừ', 'Phép nhân đơn thức', 'Phép nhân đa thức'],
    'Chương 2. Hằng đẳng thức đáng nhớ': ['Bình phương tổng', 'Bình phương hiệu', 'Hiệu hai bình phương', 'Lập phương tổng', 'Lập phương hiệu', 'Tổng lập phương', 'Hiệu lập phương', 'Vận dụng hằng đẳng thức'],
    'Chương 3. Phân thức đại số': ['Khái niệm', 'Điều kiện xác định', 'Rút gọn', 'Quy đồng', 'Cộng', 'Trừ', 'Nhân', 'Chia'],
    'Chương 4. Hàm số và đồ thị': ['Khái niệm hàm số', 'Mặt phẳng tọa độ', 'Đồ thị', 'Hàm số bậc nhất'],
    'Chương 5. Tứ giác': ['Tứ giác', 'Hình thang', 'Hình bình hành', 'Hình chữ nhật', 'Hình thoi', 'Hình vuông'],
    'Chương 6. Diện tích': ['Diện tích tam giác', 'Diện tích hình thang', 'Diện tích hình bình hành', 'Diện tích hình thoi'],
    'Chương 7. Tam giác đồng dạng': ['Định lí Thales', 'Tam giác đồng dạng', 'Các trường hợp đồng dạng', 'Ứng dụng'],
    'Chương 8. Hình chóp': ['Hình chóp tam giác đều', 'Hình chóp tứ giác đều', 'Diện tích xung quanh', 'Thể tích'],
    'Chương 9. Xác suất': ['Phép thử', 'Biến cố', 'Xác suất'],
  },
  9: {
    'Chương 1. Căn thức': ['Căn bậc hai', 'Căn bậc ba', 'Biến đổi căn thức', 'Rút gọn', 'Trục căn thức'],
    'Chương 2. Hàm số': ['Hàm số bậc nhất', 'Đồ thị', 'Hệ số góc', 'Ứng dụng'],
    'Chương 3. Hệ thức lượng': ['Tỉ số lượng giác', 'Hệ thức lượng', 'Giải tam giác vuông'],
    'Chương 4. Đường tròn': ['Góc ở tâm', 'Cung', 'Dây', 'Tiếp tuyến', 'Góc nội tiếp'],
    'Chương 5. Phương trình': ['Phương trình bậc nhất', 'Phương trình quy về bậc nhất', 'Bài toán bằng phương trình'],
    'Chương 6. Hệ phương trình': ['Hệ hai phương trình', 'Phương pháp thế', 'Phương pháp cộng', 'Bài toán thực tế'],
    'Chương 7. Thống kê': ['Tần số', 'Tần suất', 'Biểu đồ', 'Trung bình cộng'],
    'Chương 8. Xác suất': ['Không gian mẫu', 'Biến cố', 'Xác suất'],
  },
  10: {
    'Chương 1. Mệnh đề và tập hợp': ['Mệnh đề', 'Tập hợp', 'Các phép toán trên tập hợp'],
    'Chương 2. Bất phương trình': ['Bất phương trình bậc nhất hai ẩn', 'Miền nghiệm', 'Hệ bất phương trình'],
    'Chương 3. Hàm số': ['Hàm số', 'Hàm số bậc hai', 'Đồ thị', 'Biến thiên'],
    'Chương 4. Hệ thức lượng': ['Giá trị lượng giác', 'Định lí sin', 'Định lí cos', 'Diện tích tam giác'],
    'Chương 5. Vectơ': ['Khái niệm', 'Phép cộng', 'Phép trừ', 'Tích với số', 'Tích vô hướng'],
    'Chương 6. Tọa độ': ['Phương trình đường thẳng', 'Khoảng cách', 'Góc'],
    'Chương 7. Thống kê': ['Mẫu số liệu', 'Trung vị', 'Tứ phân vị', 'Độ lệch'],
    'Chương 8. Xác suất': ['Quy tắc đếm', 'Hoán vị', 'Chỉnh hợp', 'Tổ hợp', 'Xác suất'],
  },
  11: {
    'Chương 1. Hàm số lượng giác': ['Góc lượng giác', 'Hàm sin', 'Cos', 'Tan', 'Phương trình lượng giác cơ bản'],
    'Chương 2. Dãy số': ['Dãy số', 'Cấp số cộng', 'Cấp số nhân'],
    'Chương 3. Giới hạn': ['Giới hạn dãy số', 'Giới hạn hàm số', 'Hàm số liên tục'],
    'Chương 4. Đường thẳng và mặt phẳng': ['Quan hệ cơ bản', 'Giao tuyến', 'Thiết diện'],
    'Chương 5. Quan hệ song song': ['Song song', 'Định lí', 'Khoảng cách'],
    'Chương 6. Phép biến hình': ['Phép tịnh tiến', 'Phép quay', 'Phép đối xứng', 'Phép vị tự'],
    'Chương 7. Quan hệ vuông góc': ['Vuông góc', 'Góc', 'Khoảng cách'],
    'Chương 8. Xác suất': ['Biến cố', 'Xác suất có điều kiện', 'Công thức xác suất toàn phần', 'Công thức Bayes'],
  },
  12: {
    'Chương 1. Ứng dụng đạo hàm': ['Tính đơn điệu', 'Cực trị', 'Giá trị lớn nhất, nhỏ nhất', 'Tiệm cận', 'Khảo sát và vẽ đồ thị'],
    'Chương 2. Vectơ và tọa độ trong không gian': ['Vectơ không gian', 'Tích vô hướng', 'Tích có hướng', 'Hệ tọa độ Oxyz'],
    'Chương 3. Nguyên hàm': ['Khái niệm', 'Bảng nguyên hàm', 'Phương pháp tính'],
    'Chương 4. Tích phân': ['Định nghĩa', 'Tính tích phân', 'Diện tích hình phẳng', 'Thể tích khối tròn xoay'],
    'Chương 5. Phương pháp tọa độ trong không gian': ['Mặt phẳng', 'Đường thẳng', 'Mặt cầu', 'Khoảng cách', 'Góc'],
    'Chương 6. Xác suất': ['Biến ngẫu nhiên', 'Kỳ vọng', 'Phương sai'],
    'Chương 7. Thống kê': ['Mẫu ghép nhóm', 'Các số đặc trưng', 'Ước lượng thống kê'],
  },
};

module.exports = VN_MATH_CURRICULUM;
